### ISSUE TITLE
"window" is not available during server side rendering

### ISSUE THREAD

**Issue by Danm72** [Halo-Lab/useResizing#1]
WebpackError: ReferenceError: window is not defined

https://github.com/gatsbyjs/gatsby/issues/309

**Comment by stackoverprof** [comment]
I can work it well with next.js framework which is server-side rendering enabled, even with server-side generation. I don't think it can be any trouble. And also 'window' are only available when it come to the browser.

**Comment by stackoverprof** [comment]
I think you should specify your own case, and your code need to be reviewed
